version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlvt
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql-static/data
