version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./mlvt.db:/app/mlvt.db
    environment:
      - LOG_LEVEL=info
      - LOG_PATH=/app/logs/app.log
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite
    volumes:
      - ./mlvt.db:/db/mlvt.db
    command: sqlite3 /db/mlvt.db
    restart: always

